<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7967" started-at="2021-02-15T15:56:33Z" finished-at="2021-02-15T15:56:41Z">
    <groups>
      <group name="demo">
        <method signature="AppTest.testAppB()[pri:0, instance:com.rajiv.test.RestAssuredTestNG.AppTest@604ed9f0]" name="testAppB" class="com.rajiv.test.RestAssuredTestNG.AppTest"/>
      </group> <!-- demo -->
    </groups>
    <test name="Default test" duration-ms="7967" started-at="2021-02-15T15:56:33Z" finished-at="2021-02-15T15:56:41Z">
      <class name="com.rajiv.test.RestAssuredTestNG.AppTest">
        <test-method status="PASS" signature="testAppB()[pri:0, instance:com.rajiv.test.RestAssuredTestNG.AppTest@604ed9f0]" name="testAppB" duration-ms="5438" started-at="2021-02-15T15:56:33Z" finished-at="2021-02-15T15:56:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppB -->
        <test-method status="PASS" signature="myTest(int, int, int)[pri:1, instance:com.rajiv.test.RestAssuredTestNG.AppTest@604ed9f0]" name="myTest" duration-ms="7" started-at="2021-02-15T15:56:39Z" data-provider="data-provider" finished-at="2021-02-15T15:56:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method status="FAIL" signature="myTest(int, int, int)[pri:1, instance:com.rajiv.test.RestAssuredTestNG.AppTest@604ed9f0]" name="myTest" duration-ms="7" started-at="2021-02-15T15:56:39Z" data-provider="data-provider" finished-at="2021-02-15T15:56:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [9]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.rajiv.test.RestAssuredTestNG.AppTest.myTest(AppTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method status="PASS" signature="testAppA()[pri:2, instance:com.rajiv.test.RestAssuredTestNG.AppTest@604ed9f0]" name="testAppA" duration-ms="2468" started-at="2021-02-15T15:56:39Z" finished-at="2021-02-15T15:56:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAppA -->
      </class> <!-- com.rajiv.test.RestAssuredTestNG.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
